name: Publish to GHCR
on:
    push:
        branches: ["main"]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Log in to the Container registry
              uses: docker/login-action@v4
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v7
              with:
                  push: true
                  context: .
                  file: dist/Containerfile
                  tags: ghcr.io/progval/matrix2051:latest
